sbc/clients/urls.py
from django.urls import path

from .views import (
    create_client_profile,
    got_success,
    view_forms_list,
    CitizenView,
    CitizenDeleteView,
    CitizenSendEmail,
    search_client_view,
    root,
)
    # about_citizen,

app_name = 'clients'

urlpatterns = [
    path('', root, name="root"),
    path('clients/create/', create_client_profile, name='create_client_profile'),
    path('clients/success/', got_success, name='got_success'),
    path('clients/', view_forms_list, name='view_forms_list'),
    path('clients/<int:id>/', CitizenView.as_view(), name='client_detail'),
    path('clients/<int:id>/edit/', CitizenView.as_view(template_name = "clients/edit_citizen.html"), name='edit_citizen'),
    path('clients/<int:id>/delete/', CitizenDeleteView.as_view(), name='citizen-delete'),
    path('clients/search/', search_client_view, name='search-citizen'),
    path('clients/<int:id>/email/',  CitizenSendEmail.as_view(), name='send_email')


    # path('<int:id>/edit', edit_form, name='edit_form')
    # path('<str:firstname>/', about_citizen, name='about_citizen')

]

sbc/sbc/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('clients.urls'))
]

sbc/users/urls.py
from django.urls import path

from .views import main, login_user, create_user_profile, logout_user

app_name = 'users'


urlpatterns = [
    path('', main, name='main'),
    path('login/', login_user, name='login_user'),
    path('signup/', create_user_profile, name='create_user_profile'),
    path('logout/', logout_user, name='logout_user'),
]

sbc/templates/sbc/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
     {% load static %}
    <link rel="stylesheet" href="{% static 'sbc/style.css' %}">


    <title> Django Project! </title>
</head>
<body>
{% include 'sbc/navbar.html' %}



{% block content%} Your content here {% endblock %}

<!--<div class="footer">{% include 'sbc/footer.html' %}</div>-->
<!--{% include 'sbc/footer.html' %}-->

</body>
</html>

sbc/templates/sbc/footer.html
<style>
.row {
  padding: 1em 1em;
}
.row.primary {
  background-color: #17787F;
  display: grid;
  grid-template-columns: 3fr 2fr 4fr;
  align-items: stretch;
}
.column {
  width: 100%;
  display: flex;
  flex-direction: column;
  padding: 0 2em;
  min-height: 15em;
}
h3 {
  width: 100%;
  text-align: left;
  color: white;
  font-size: 1.4em;
  white-space: nowrap;
}
ul {
  list-style: none;
  display: flex;
  flex-direction: column;
  padding: 0;
  margin: 0;
}
li:not(:first-child) {
  margin-top: 0.8em;
}
ul li a {
  color: #a7a7a7;
  text-decoration: none;
}
ul li a:hover {
  color: #c7940a;
}
.about p {
  text-align: justify;
  line-height: 2;
  margin: 0;
}
input,
button {
  font-size: 1em;
  padding: 1em;
  width: 100%;
  border-radius: 5px;
  margin-bottom: 5px;
}
button {
  background-color: #c7940a;
  color: #ffffff;
}
div.social {
  display: flex;
  justify-content: space-around;
  font-size: 2.4em;
  flex-direction: row;
  margin-top: 0.5em;
}
.social i {
  color: #bac6d9;
}

.copyright {
  padding: 0.3em 1em;
  background-color: #25262e;
}

.footer-menu{
  float: left;
    margin-top: 10px;
}
.footer-menu a{
  color: #cfd2d6;
  padding: 6px;
  text-decoration: none;
}
.footer-menu a:hover, .social i:hover{
  color: #c7940a;
}
.copyright p {
  font-size: 0.9em;
  text-align: right;
}

@media screen and (max-width: 850px) {
  .row.primary {
    grid-template-columns: 1fr;
  }
}

</style>



<div class="row primary">
  <div class="column about">
    <h3>Connect</h3>
    <p>
      <i class="fa fa-map-marker" aria-hidden="true"></i>
      Andrii OSA Ukraine Mykolaiv
    </p>
    <div class="social">
      <i class="fa fa-facebook-square"></i>
      <i class="fa fa-twitter-square"></i>
      <i class="fa fa-linkedin-square"></i>
      <i class="fa fa-instagram"></i>
    </div>
  </div>

  <div class="column link">
    <h3>Links</h3>
    <ul>
      <li><a href="#home">Home</a></li>
      <li><a href="#team">Team</a></li>
      <li><a href="#blogs">Blogs</a></li>
      <li><a href="#support">Support</a></li>
    </ul>
  </div>

  <div class="column subscribe">
    <h3>Newsletter</h3>
    <div>
      <input type="email" placeholder="Your email id here" />
      <button>Subscribe</button>
    </div>
  </div>
</div>
<div class="row copyright">
  <div class="footer-menu">

  <a href="">Home</a>
  <a href="">F.A.Q</a>
  <a href="">Cookies Policy</a>
  <a href="">Terms Of Service</a>
  <a href="">Support</a>

  </div>
   <p>Copyright &copy; 2023</p>
</div>

</body>
</html>

sbc/templates/sbc/index.html
{% extends 'sbc/base.html' %}

{% block content%} {% endblock %}

sbc/templates/sbc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="navbar-brand">Navbar scroll</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
<!--      <button-->
<!--            class="navbar-toggler"-->
<!--            type="button"-->
<!--            data-toggle="collapse"-->
<!--            data-target="#navbarScroll"-->
<!--            aria-controls="navbarScroll"-->
<!--            aria-expanded="false"-->
<!--            aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="{% url 'clients:create_client_profile' %}" type="button" class="btn btn-info" style="padding: 5px 10px;  margin-left: 10px;">Create Citizen Form</a>
        </li>
         {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'clients:view_forms_list' %}" type="button" class="btn btn-info" style="padding: 5px 10px;  margin-left: 10px;">View Citizens Forms</a>
        </li>
        {% endif %}
      </ul>


      <form class="d-flex" role="search" method="GET" action="{{ get_absolute_url }}/clients/search/">
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
     <button class="btn btn-outline-success" type="submit" class="btn btn-warning" style="padding: 5px 10px;">Search</button>
      </form>


      {% if user.is_authenticated %}
    <a href="{% url 'users:logout_user' %}" type="button" class="btn btn-warning" style="padding: 5px 10px;  margin-left: 10px;">Logout</a>
      {% else %}
    <a href="{% url 'users:login_user' %}" type="button" class="btn btn-secondary" class="btn btn-warning" style="padding: 5px 10px;  margin-left: 10px;">Login</a>
    <a href="{% url 'users:create_user_profile' %}" type="button" class="btn btn-success" class="btn btn-warning" style="padding: 5px 10px;  margin-left: 10px;">Sign Up</a>
      {% endif %}

<!--      <style>-->
<!--      /* Media query for screens with max-width 850px */-->
<!--      @media screen and (max-width: 850px) {-->
<!--        .navbar-nav {-->
<!--          flex-direction: column;-->
<!--        }-->
<!--        .navbar-toggler {-->
<!--          order: 3;-->
<!--        }-->
<!--        .collapse.navbar-collapse {-->
<!--          order: 4;-->
<!--        }-->
<!--        .navbar-nav-scroll {-->
<!--          max-height: 200px;-->
<!--          overflow-y: auto;-->
<!--        }-->
<!--        .navbar-nav-scroll li {-->
<!--          margin-bottom: 10px;-->
<!--        }-->
<!--        .navbar-nav-scroll li:last-child {-->
<!--          margin-bottom: 0;-->
<!--        }-->
<!--        .navbar-nav-scroll li a {-->
<!--          padding: 5px;-->
<!--        }-->
<!--      }-->
<!--    </style>-->

    </div>
  </div>
</nav>