sbc/clients/urls.py
from django.urls import path

from .views import (
    create_client_profile,
    got_success,
    view_forms_list,
    CitizenView,
    CitizenDeleteView,
    CitizenSendEmail,
    search_client_view,
    root,
)
    # about_citizen,

app_name = 'clients'

urlpatterns = [
    path('', root, name="root"),
    path('clients/create/', create_client_profile, name='create_client_profile'),
    path('clients/success/', got_success, name='got_success'),
    path('clients/', view_forms_list, name='view_forms_list'),
    path('clients/<int:id>/', CitizenView.as_view(), name='client_detail'),
    path('clients/<int:id>/edit/', CitizenView.as_view(template_name = "clients/edit_citizen.html"), name='edit_citizen'),
    path('clients/<int:id>/delete/', CitizenDeleteView.as_view(), name='citizen-delete'),
    path('clients/search/', search_client_view, name='search-citizen'),
    path('clients/<int:id>/email/',  CitizenSendEmail.as_view(), name='send_email')


    # path('<int:id>/edit', edit_form, name='edit_form')
    # path('<str:firstname>/', about_citizen, name='about_citizen')

]

sbc/sbc/urls.py
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('', include('clients.urls'))
]

sbc/clients/models.py
from django.db import models
from django.urls import reverse


class Stage(models.Model):

    TYPE_STAGES = (
        ('Unknown', 'unknown'),
        ('Accept', 'accept'),
        ('Refuse', 'refuse'),
        ('Onhold', 'onhold'),
    )

    type = models.CharField(choices=TYPE_STAGES, default='Unknown')

    def __str__(self):
        return f'{self.type}'



# Create your models here.
class Citizen(models.Model):

    firstname = models.CharField(max_length=100, blank=False, null=False)
    lastname = models.CharField(max_length=100, blank=False, null=False)
    email = models.EmailField(max_length=255, unique=False, null=False)
    telephone_num = models.CharField(max_length=13, blank=False, null=True)
    age = models.IntegerField()
    note = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE, default=16)


    def __str__(self):
        return f'{self.firstname} {self.lastname} {self.is_active}'


    def get_absolute_url(self):
        return reverse("clients:citizen-detail", kwargs={"id": self.id})

sbc/clients/forms.py
from django import forms
from .models import Citizen, Stage


class CreateCitizen(forms.ModelForm):
    firstname = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))


    lastname = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))


    email = forms.EmailField(max_length=100,
                             required=True,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    telephone_num = forms.CharField(max_length=13,
                                    required=False,
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))

    age = forms.IntegerField(min_value=21,
                             max_value=120,
                             required=True,
                             widget=forms.NumberInput(attrs={'class': 'form-control'}))

    note = forms.CharField(max_length=1200,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    # widjet filter type = unknown
    # Stage.objects.all(), -> if un authenticated or role = guest
    # add phone address to models
    # add app services
    #Foreign key services - clients

    # stage = forms.ModelChoiceField(queryset=Stage.objects.all(),
    #                                widget=forms.Select(attrs={'class': 'form-select'}))

    class Meta:
        model = Citizen
        fields = ['firstname', 'lastname', 'email', 'telephone_num', 'age', 'note']




class EditCitizen(forms.ModelForm):
    firstname = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))

    lastname = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))

    email = forms.EmailField(max_length=100,
                             required=True,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    telephone_num = forms.CharField(max_length=13,
                                    required=False,
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))

    age = forms.IntegerField(min_value=21,
                             max_value=120,
                             required=True,
                             widget=forms.NumberInput(attrs={'class': 'form-control'}))

    note = forms.CharField(max_length=1200,
                           required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))



    stage = forms.ModelChoiceField(queryset=Stage.objects.all(),
                                   widget=forms.Select(attrs={'class': 'form-select'}))

    class Meta:
        model = Citizen
        fields = ['firstname', 'lastname', 'email', 'telephone_num', 'age', 'note', 'stage']




class SendEmailForm(forms.ModelForm):

    coppy_to = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))

    theme = forms.CharField(max_length=200,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))



    text = forms.CharField(max_length=2400,
                           required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control'}))


    attachment = forms.FileField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-select'})
    )

    class Meta:
        model = Citizen
        fields = ['coppy_to', 'theme', 'text', 'attachment']

sbc/clients/views.py
import os
import smtplib
import ssl
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.mail import EmailMessage
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.views import View

from .forms import CreateCitizen, EditCitizen, SendEmailForm
from .models import Citizen
from dotenv import dotenv_values


CONFIG = dotenv_values('.env')
MetaLogin = CONFIG.get("MetaLogin")
MetaPassword = CONFIG.get("MetaPassword")




def root(request):
    return render(request, "clients/index.html", {})

def create_client_profile(request):


    if request.method == 'POST':
        form = CreateCitizen(request.POST)
        if form.is_valid():
            form.save()
            return redirect('clients:got_success')
        else:
            return render(request, 'clients/create_citizen.html', context={"form": form})

    form = CreateCitizen()
    return render(request, 'clients/create_citizen.html', context={"form": form})


def got_success(request):
    return render(request, 'clients/success_page.html', {})



# def edit_client_profile(request):


def view_forms_list(request, page=1):


    citizens_model = Citizen.objects.all()

    # per_page = 100
    # paginator = Paginator(list(citizens_model), per_page)
    # citizens_on_page = paginator.page(page)
    return render(request, 'clients/list.html', {"citizens": citizens_model})



class CitizenObjectMixin(object):
    model = Citizen
    def get_object(self):
        _id = self.kwargs.get('id')
        obj = None
        if _id is not None:
            obj = get_object_or_404(self.model, pk=_id)
        return obj

    def get_id(self):
        return self.kwargs.get("id")


class CitizenView(CitizenObjectMixin, View):
    template_name = "clients/citizen_page.html"   # DetailView
    def get(self, request, id=None, *args, **kwargs):
        citizen = self.get_object()
        # print(f'!!!!!!!!!!!!!{citizen}')
        # GET method
        if self.template_name == 'clients/edit_citizen.html':
            citizen = get_object_or_404(Citizen, pk=id)
            form = EditCitizen()
            return render(request, 'clients/edit_citizen.html', context={"form": form, "citizen": citizen})
        context = {'citizen': citizen}
        return render(request, self.template_name, context)


    def post(self, request, id):
        if request.method == 'POST':
            form = EditCitizen(request.POST)
            print("I am in the POST")
            if form.is_valid():
                # form.save()
                self.update_citizen_view(form.cleaned_data)
                # print(form.cleaned_data.get('firstname'))
                return redirect('clients:view_forms_list')
            else:
                return render(request, 'clients/edit_citizen.html', context={"form": form})

        # obj = CitizenObjectMixin()
        # citizen_obj = obj.get_object()
        print("I am in the GET")
        citizen = get_object_or_404(Citizen, pk=id)
        form = EditCitizen()
        return render(request, 'clients/edit_citizen.html', context={"form": form, "citizen": citizen})



    def update_citizen_view(self, data: dict):
        citizen = self.get_object()
        # _id = self.get_id()
        # Citizen.objects.update_or_create(pk=_id, defaults={'firstname': data.get("firstname"),
        #                                                    "lastname": data.get("lastname"),
        #                                                    "email": data.get("email"),
        #                                                    "telephone_num": data.get("telephone_num"),
        #                                                    "age": data.get("age"),
        #                                                    "note": data.get("note"),
        #                                                    "stage": data.get("stage"),
        #                                                     })

        citizen.firstname = data.get('firstname')
        citizen.lastname = data.get('lastname')
        citizen.email = data.get('email')
        citizen.telephone_num = data.get('telephone_num')
        citizen.age = data.get('age')
        citizen.note = data.get('note')
        citizen.stage = data.get('stage')

        citizen.save()
        print('Update was successful')

    # def remove_citizen_view(self):
    #     citizen = self.get_object()
    #     citizen.delete()
    #     print('Deleting citizen form was successful')



class CitizenDeleteView(CitizenObjectMixin, View):
    template_name = 'clients/delete_citizen.html' # DetailView
    def get(self, request, id=None, *args, **kwargs):
        # GET method
        context = {}
        obj = self.get_object()
        if obj is not None:
            context['object'] = obj
        return render(request, self.template_name, context)

    def post(self, request, id=None,  *args, **kwargs):
        # POST method
        context = {}
        obj = self.get_object()
        if obj is not None:
            obj.delete()
            context['object'] = None
            print(context)
            return redirect('/clients/')
        return render(request, self.template_name, context)




def search_client_view(request):
    query = request.GET.get("q")
    print(query)
    citizens_model = Citizen.objects.filter(
        Q(firstname__icontains=query) |
        Q(lastname__icontains=query) |
        Q(email__icontains=query) |
        Q(telephone_num__icontains=query)

    )
    return render(request, 'clients/list.html', {"citizens": citizens_model})



def about_citizen(request, firstname):
    print('I Am in about_citizen Func!!!!!!!!!!!!')
    citizen = Citizen.objects.get(firstname=firstname)
    print(citizen)
    return render(request, "clients/citizen_page.html", {"citizen": citizen})




class CitizenSendEmail(CitizenObjectMixin, View):
    template_name = 'clients/send_email.html' # DetailView
    def get(self, request, id=None, *args, **kwargs):
        # GET method
        print('I am get method')
        context = {}
        obj = self.get_object()
        form = SendEmailForm()
        if obj is not None:
            context['object'] = obj

        return render(request, self.template_name, context={"form": form,"object": obj})

    def post(self, request, id=None,  *args, **kwargs):
        # POST method
        print('I am post method')
        context = {}
        obj = self.get_object()
        if obj is not None:
            self.send_email(request, obj)
            context['object'] = None
            return redirect('/clients/')
        return render(request, self.template_name, context)

    def handle_uploaded_file(self, file: InMemoryUploadedFile):
        # Generate a unique file name
        file_name = file.name
        upload_folder_path = "uploads/"
        if not os.path.exists(upload_folder_path):
            os.mkdir(upload_folder_path)

        file_path = upload_folder_path + file_name

        # Read the file contents
        file_contents = file.read()

        # Save the file to disk
        with open(file_path, 'wb') as destination:
            destination.write(file_contents)


        return file_path


    def send_email(self, request, obj):
        if request.method == 'POST':
            print('I am in send email POST method!')
            form = SendEmailForm(request.POST, request.FILES)
            if form.is_valid():
                # File upload handling logic

                attachment_file: InMemoryUploadedFile = form.cleaned_data['attachment']
                file_path = self.handle_uploaded_file(attachment_file)
                # Process the file as needed
                print('I am in sending email form is OK!')
                print(form.cleaned_data)

                run_send_email(obj, form.cleaned_data, file_path)
                return render(request, 'clients/success_page.html')
        else:
            form = SendEmailForm()
        return render(request, 'clients/send_email.html', {'form': form})



def run_send_email(obj: Citizen, data: dict, file_path: str):

    user_name = obj.firstname + " " + obj.lastname
    print(user_name)
    Host = 'smtp.meta.ua'
    Port = 465
    Sender = MetaLogin
    Sender_password = MetaPassword


    # Enter your address
    receiver_email = obj.email
    subject = f"Subject: Greetings, dear {user_name}, {data['theme']}"
    message = data['text']

    # mail = EmailMessage(subject=subject, body=message, from_email=Sender, to=[receiver_email],
    #                     cc=[data.get('coppy_to')])


    attachment_name = os.path.basename(file_path)

    with open(file_path, 'rb') as attachment:
        mail = EmailMessage(subject=subject, body=message, from_email=Sender, to=[receiver_email],
                            cc=[data.get('coppy_to')])
        mail.attach(attachment_name, attachment.read(), data.get('attachment').content_type)
        mail.send()

    # mail.attach(data.get('attachment').name, data.get('attachment').read(), data.get('attachment').content_type)
    # mail.send()

      # Enter receiver address
    # password = input("Type your password and press enter: ")
    # email_message = f"Subject: Hi {message.get('payload')[0]}\n {message.get('text')}"
    # context = ssl.create_default_context()
    # with smtplib.SMTP_SSL(Host, Port, timeout=30) as server:
    #     try:
    #         # context.check_hostname = False
    #         # server.starttls(context=context)
    #
    #         server.login(Sender, Sender_password)
    #
    #         message = MIMEMultipart()
    #         message['From'] = Sender
    #         message['To'] = receiver_email

sbc/clients/templates/clients/citizen_page.html
{% extends "sbc/base.html" %}

<style>

.btn.btn-primary {
    background-color: #1CC3C3;
    color: #DDFDFD;
    padding: 10px 20px;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
}

</style>

{% block content %}
<div class="container m-10">
    <div class="text-left">
        <h1>{{ citizen.firstname}}{{citizen.lastname}}</h1>
        <p><label for="email">Email:</label> <span id="email">{{citizen.email}}</span></p>
        <p><label for="telephone_num">Tel.:</label> <span id="telephone_num">{{citizen.telephone_num}}</span></p>
        <p><label for="age">Age:</label> <span id="age">{{citizen.age}}</span></p>
        <p><label for="note">Note:</label> <span id="note">{{citizen.note}}</span></p>
        <p><label for="is_active">Status:</label> <span id="is_active">{{citizen.is_active}}</span></p>
        <p><label for="created_at">Date:</label> <span id="created_at">{{citizen.created_at}}</span></p>
        <p><label for="stage">Stage:</label> <span id="stage">{{citizen.stage}}</span></p>

        <div>
        <form method="GET" action="{{ get_absolute_url }}/clients/{{ citizen.id }}/edit">
            <button type="submit" class="btn btn-outline-info" id="editButton">Edit</button>
        </form>

        <form method="GET" action="{{ get_absolute_url }}/clients/{{ citizen.id }}/delete">
            <button type="submit" class="btn btn-outline-info" id="DeleteButton">Delete</button>
        </form>

        <form method="GET" action="{{ get_absolute_url }}/clients/{{ citizen.id }}/email">
            <button type="submit" class="btn btn-outline-info" id="EmailButton">Send Email</button>
        </form>
        </div>

        <!--        <a class="btn-primary" href="{{get_absolute_url}}/clients/{{citizen.id}}/edit" id="editButton">Edit</a>-->
    </div>
</div>

{% endblock %}

sbc/clients/templates/clients/create_citizen.html
{% extends "sbc/base.html" %}

{% block content %}
<h1>Create Citizen</h1>

<div class="container col-md-6">
    <div class="text-center">


    <form method="post" action="{% url 'clients:create_client_profile' %}">
        {% csrf_token %}


        <div>
            <label> First name:
                {{ form.firstname }}
            </label>
            <span>{{ form.errors.firstname }}</span>
        </div>

        <div>
            <label> Last name:
                {{ form.lastname }}
            </label>
            <span>{{ form.errors.lastname }}</span>
        </div>

        <div>
            <label> Email:
                {{ form.email }}
            </label>
            <span>{{ form.errors.email }}</span>
        </div>

        <div>
            <label> Phone number:
                {{ form.telephone_num }}
            </label>
            <span>{{ form.errors.telephone_num }}</span>
        </div>

        <div>
            <label> Age:
                {{ form.age }}
            </label>
            <span>{{ form.errors.age }}</span>
        </div>

        <div>
            <label> Note:
                {{ form.note }}
            </label>
            <span>{{ form.errors.note }}</span>
        </div>

        <hr>
        <div class="grid">
            <button type="submit" class="btn btn-outline-success" style="padding: 5px 10px; margin: 5px 0px;">Submit
            </button>
            <button type="reset" class="btn btn-outline-danger" style="padding: 5px 10px; margin: 5px 5px;">Reset
            </button>
        </div>
    </form>
</div>

{% endblock %}

sbc/clients/templates/clients/delete_citizen.html
{% extends "sbc/base.html" %}

{% block content %}

<form action='.' method='POST'>{% csrf_token %}
    <h1>Do you want to delete the user "{{ object.firstname }}{{ object.lastname }} with Email: {{ object.email }}"?</h1>
    <p><input type='submit' value='Yes' />  <a href='../../'>Cancel</a></p>

</form>

{% endblock %}

sbc/clients/templates/clients/edit_citizen.html
{% extends "sbc/base.html" %}

{% block content %}
<h1>EDIT PAGE</h1>
<div class="container m-10">
    <div class="text-left">
        <form method="post">
            {% csrf_token %}
            <div class="container col-md-8" style="border: 2px solid black;">

                <div>
                    <label> First name:
                         <input class="form-control form-control-lg" id="firstname" value='{{citizen.firstname}}'
                               name="firstname" size=80>

                    </label>
                    <span>{{ form.errors.firstname }}</span>
                </div>

                <div>
                    <label> Last name:
                        <input class="form-control form-control-lg" id="lastname" value='{{citizen.lastname}}'
                               name="lastname" size=80>
                    </label>

                    <span>{{ form.errors.lastname }}</span>
                </div>

                <div>
                    <label> Email:
                        <input class="form-control form-control-lg" id="email" value='{{citizen.email}}'
                               name="email" size=80>
                    </label>
                    <span>{{ form.errors.email }}</span>
                </div>

                <div>
                    <label> Phone number:
                        <input class="form-control form-control-lg" id="telephone_num" value='{{citizen.telephone_num}}'
                               name="telephone_num" size=80>
                    </label>
                    <span>{{ form.errors.telephone_num }}</span>
                </div>

                <div>
                    <label> Age:
                        <input class="form-control form-control-lg" id="age" value='{{citizen.age}}'
                               name="age" size=80>
                    </label>
                    <span>{{ form.errors.age }}</span>
                </div>

                <div>
                    <label> Note:
                        <input class="form-control form-control-lg" id="note" value='{{citizen.note}}'
                               name="note" size=80>
                    </label>
                    <span>{{ form.errors.note }}</span>
                </div>


                <div>
                    <label> Stage:
                        <p><span id="stage">{{form.stage}}</span></p>
                    </label>
                    <span>{{ form.errors.stage }}</span>
                </div>

                <div class="grid">
                    <button type="submit" class="btn btn-outline-success"
                            style="padding: 5px 10px; margin: 5px 0px;">Submit
                    </button>
                    <button type="reset" class="btn btn-outline-danger" style="padding: 5px 10px; margin: 5px 5px;">
                        Reset
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

    {% endblock %}

sbc/clients/templates/clients/index.html
{% extends 'sbc/base.html' %}


{% block content%}


<div class="container m-12">
  <img src="https://www.countryflags.com/wp-content/uploads/ukraine-flag-png-large.png" class="mx-auto d-block">
</div>
</div> {% endblock %}

sbc/clients/templates/clients/list.html
{% extends "sbc/base.html" %}

{% block content %}
<style>
  .scroll-table-body {
 height: 700px;
 overflow-x: auto;
 margin-top: 0px;

 margin-bottom: 20px;
 border-bottom: 1px solid #eee;
}
.scroll-table table {
 width:100%;
 table-layout: fixed;
 border: 1px solid #ddd;

}
.scroll-table thead th {
 font-weight: bold;
 text-align: center;
 border: none;
 padding: 10px 15px;

 background: #07A1C0;
 font-size: 14px;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
}
.scroll-table tbody td {
 text-align: left;
 border-left: 1px solid #ddd;
 border-right: 1px solid #ddd;
 padding: 10px 15px;
 font-size: 14px;
 vertical-align: top;
}
.scroll-table tbody tr:nth-child(even){
 background: #f3f3f3;
}

.table {
        background-color: #C5F2F3;
        padding: 10px;
        color: #DE00FF;
    }

.my-table {
        background-color: #C5F2F3;
        padding: 10px;
        color: #616161;
}



/* Стили для скролла */
::-webkit-scrollbar {
 width: 6px;
}
::-webkit-scrollbar-track {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
::-webkit-scrollbar-thumb {
 box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
}
</style>

<div class="container m-10">
    <div class="text-center">
        <div class="scroll-table">
            <table class="table">
                <thead>
                <tr class="tr">
                    <th scope="col">firstname</th>
                    <th scope="col">lastname</th>
                    <th scope="col">email</th>
                    <th scope="col">telephone_num</th>
                    <th scope="col">age</th>
                    <th scope="col">note</th>
                    <th scope="col">is_active</th>
                    <th scope="col">created_at</th>
                    <th scope="col">stage</th>
                </tr>
                </thead>
            </table>

            <div class="scroll-table-body">
                <table class="my-table">
                    <tbody class="my_tr">

                    {% for citizen in citizens %}
                    <tr>
                        <td><a href="{% url 'clients:client_detail' citizen.id %}">{{citizen.firstname}}</a></td>
                        <td>{{citizen.lastname}}</td>
                        <td>{{citizen.email|truncatechars:15}}</td>
                        {% if  citizen.telephone_num != 'None' %}
                            <td>{{citizen.telephone_num}}</td>
                        {% else %}
                            <td>- - - -</td>
                        {% endif %}
                        <td>{{citizen.age}}</td>
                        <td>{{citizen.note}}</td>
                        <td>{{citizen.is_active}}</td>
                        <td>{{citizen.created_at}}</td>
                        <td>{{citizen.stage}}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


        {% endblock %}

sbc/clients/templates/clients/send_email.html
{% extends "sbc/base.html" %}

{% block content %}

<div class="container m-10">
    <div class="text-left">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

sbc/clients/templates/clients/success_page.html
{% extends "sbc/base.html" %}

{% block content %}

<h1>Thank you for registration your form!</h1>

<h2>Kindly wait for our manager contact with you!</h2>

{% endblock content %}